### ISSUE TITLE
issue when install spconv1.0 as mentioned in TALoS

### ISSUE THREAD

**Issue by ConnorKevin** [blue-531/TALoS#3]
Thank you for your prompt response!

I am still encountering a problem while installing spconv1.0. My current versions are CMake 3.13.2 and PyTorch 1.10.0.

```
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/src/spconv/all.cc:20:91: error: no matching function for call to ‘torch::jit::RegisterOperators::RegisterOperators(const char [28], <unresolved overloaded function type>)’
   20 |     torch::jit::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)
```

My cmake is 3.13.2, PyTorch is 1.10.0,  and 

```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

I noticed a similar issue discussed here: https://github.com/open-mmlab/OpenPCDet/issues/187 regarding another version of spconv1.0. Additionally, some suggested solutions involve replacing "torch::jit::RegisterOperators" with "torch::RegisterOperators" as mentioned in this link: https://github.com/pytorch/extension-script/issues/6.

I would like to know how this issue was addressed during TALoS testing. Furthermore, I hope that more detailed installation guidance will be released soon～

Thank you!

This is the full log:

```
$ python setup.py bdist_wheel
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running bdist_wheel
running build
running build_py
copying spconv/__init__.py -> build/lib.linux-x86_64-cpython-38/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-cpython-38/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-cpython-38/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-cpython-38/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-cpython-38/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-cpython-38/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-cpython-38/spconv
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-cpython-38/spconv/utils
running build_ext
/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/lib.linux-x86_64-cpython-38
Release
-- The CXX compiler identification is GNU 9.4.0
-- The CUDA compiler identification is NVIDIA 11.3.109
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-11.3/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.3/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-11.3 (found version "11.3") 
-- Caffe2: CUDA detected: 11.3
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.3/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.3
-- Caffe2: Header version is: 11.3
-- Found CUDNN: /usr/local/cuda-11.3/lib64/libcudnn.so  
-- Found cuDNN: v9.5.1  (include: /usr/include, library: /usr/local/cuda-11.3/lib64/libcudnn.so)
-- /usr/local/cuda-11.3/lib64/libnvrtc.so shorthash is 1ea278b5
-- Autodetected CUDA architecture(s):  8.6 8.6 8.6 8.6 8.6 8.6 8.6 8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
CMake Warning at /home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:26 (find_package)


-- Found Torch: /home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/lib/libtorch.so  
-- Found PythonInterp: /home/jiangt/anaconda3/envs/TALoS_czg/bin/python3.8 (found suitable version "3.8.20", minimum required is "3.8") 
-- Found PythonLibs: /home/jiangt/anaconda3/envs/TALoS_czg/lib/libpython3.8.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.5.dev1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38
gmake[1]: Entering directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[1]: Warning: File 'CMakeFiles/Makefile2' has modification time 0.002 s in the future
gmake[2]: Entering directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[2]: Entering directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
Scanning dependencies of target spconv
Scanning dependencies of target spconv_nms
gmake[2]: Leaving directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[2]: Entering directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[2]: Warning: File 'src/utils/CMakeFiles/spconv_nms.dir/depend.make' has modification time 0.036 s in the future
[  7%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
gmake[2]: Leaving directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[2]: Entering directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[2]: Warning: File 'src/spconv/CMakeFiles/spconv.dir/depend.make' has modification time 0.022 s in the future
[ 28%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 28%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 28%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 35%] Linking CUDA device code CMakeFiles/spconv_nms.dir/cmake_device_link.o
[ 42%] Linking CUDA shared library ../../../lib.linux-x86_64-cpython-38/spconv/libspconv_nms.so
gmake[2]: warning:  Clock skew detected.  Your build may be incomplete.
gmake[2]: Leaving directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
[ 42%] Built target spconv_nms
[ 50%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/src/spconv/all.cc:20:91: error: no matching function for call to ‘torch::jit::RegisterOperators::RegisterOperators(const char [28], <unresolved overloaded function type>)’
   20 |     torch::jit::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)
      |                                                                                           ^
In file included from /home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/script.h:7,
                 from /home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/include/spconv/pool_ops.h:20,
                 from /home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/src/spconv/all.cc:16:
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:22:12: note: candidate: ‘torch::jit::RegisterOperators::RegisterOperators(std::vector<c10::optional<torch::jit::Operator> >)’
   22 |   explicit RegisterOperators(std::vector<c10::optional<Operator>> operators) {
      |            ^~~~~~~~~~~~~~~~~
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:22:12: note:   candidate expects 1 argument, 2 provided
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:17:3: note: candidate: ‘constexpr torch::jit::RegisterOperators::RegisterOperators()’
   17 |   RegisterOperators() = default;
      |   ^~~~~~~~~~~~~~~~~
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:17:3: note:   candidate expects 0 arguments, 2 provided
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note: candidate: ‘constexpr torch::jit::RegisterOperators::RegisterOperators(const torch::jit::RegisterOperators&)’
   16 | struct TORCH_API RegisterOperators {
      |                  ^~~~~~~~~~~~~~~~~
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note:   candidate expects 1 argument, 2 provided
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note: candidate: ‘constexpr torch::jit::RegisterOperators::RegisterOperators(torch::jit::RegisterOperators&&)’
/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/torch/include/torch/csrc/jit/runtime/custom_operator.h:16:18: note:   candidate expects 1 argument, 2 provided
gmake[2]: *** [src/spconv/CMakeFiles/spconv.dir/build.make:63: src/spconv/CMakeFiles/spconv.dir/all.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Entering directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
Scanning dependencies of target spconv_utils
gmake[2]: Leaving directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[2]: Entering directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[2]: Warning: File 'src/utils/CMakeFiles/spconv_utils.dir/depend.make' has modification time 0.034 s in the future
[ 57%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
In file included from /usr/include/boost/math/tools/cxx03_warn.hpp:9,
                 from /usr/include/boost/math/constants/constants.hpp:11,
                 from /usr/include/boost/geometry/util/math.hpp:29,
                 from /usr/include/boost/geometry/core/radian_access.hpp:33,
                 from /usr/include/boost/geometry/geometry.hpp:51,
                 from /usr/include/boost/geometry.hpp:17,
                 from /home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/include/spconv/nms.h:20,
                 from /home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/src/utils/all.cc:15:
/usr/include/boost/detail/no_exceptions_support.hpp:17:1: note: #pragma message: This header is deprecated. Use <boost/core/no_exceptions_support.hpp> instead.
   17 | BOOST_HEADER_DEPRECATED("<boost/core/no_exceptions_support.hpp>")
      | ^~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: Leaving directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake[1]: *** [CMakeFiles/Makefile2:109: src/spconv/CMakeFiles/spconv.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 64%] Linking CXX shared library ../../../lib.linux-x86_64-cpython-38/spconv/spconv_utils.cpython-38-x86_64-linux-gnu.so
gmake[2]: warning:  Clock skew detected.  Your build may be incomplete.
gmake[2]: Leaving directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
[ 64%] Built target spconv_utils
gmake[1]: Leaving directory '/home/jiangt/zhuoguang/ssc_tta/TALoS/spconv1.0/build/temp.linux-x86_64-cpython-38'
gmake: *** [Makefile:130: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    setup(
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
    self.run_command("build")
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/home/jiangt/anaconda3/envs/TALoS_czg/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
```

**Comment by FrorsttzNguyen** [comment]
Hi @ConnorKevin, I'm facing the exact same issue with `spconv v1.0` while trying to survey this project. Were you able to fix this? If so, would you be willing to share the `.whl` file with me? Thank you so much!
